<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>via_entrega.services</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ICollectionOrderService.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\via-entrega.entities\via-entrega.entities.csproj" />
    <ProjectReference Include="..\via-entrega.interfaces\via-entrega.interfaces.csproj" />
    <ProjectReference Include="..\via-entrega.repositories\via-entrega.repositories.csproj" />
  </ItemGroup>

</Project>
